'use client';

import React, { useState, useEffect, useRef } from 'react';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/Card';
import { StatCard } from '@/components/ui/StatCard';
import { Cpu, Terminal, Radio, Server } from 'lucide-react';
import { useEventStore } from '@/hooks/useEventStore';

export function SystemHealth() {
  const { isStreaming } = useEventStore();
  const [logs, setLogs] = useState<string[]>([
    `[${new Date().toLocaleTimeString()}] [INFO] AEGIS System Kernel successfully initialized.`,
    `[${new Date().toLocaleTimeString()}] [INFO] Connected to Supabase direct-integration socket.`,
    `[${new Date().toLocaleTimeString()}] [INFO] RLS active. 12 operational security profiles verified.`,
  ]);
  
  const logFeedEndRef = useRef<HTMLDivElement>(null);

  // Auto-generate scrolling diagnostic logs
  useEffect(() => {
    if (!isStreaming) return;

    const logTypes = ['INFO', 'WARN', 'AI_ENGINE'];
    const mockMessages = {
      INFO: [
        'Turnstile North Gate 2 successfully processed RFID ticket.',
        'Parking Lot South connected. Available capacity: 1050 spots.',
        'Transport Metro line 1 ETA updated: 4.0 minutes wait.',
      ],
      WARN: [
        'Concourse food counters queue time exceeding 8 minutes.',
        'Elevator VIP Lift B showing increased door closure latency.',
        'Low battery warning on ground sensor unit #105.',
      ],
      AI_ENGINE: [
        'AI Co-Pilot parsed medical triage incident Sec B Entrance.',
        'AI decision model generated bypass recommendation for Gate 3 congestion.',
        'Confidence score of 94% evaluated for Medical Dispatch alpha.',
      ],
    };

    const interval = setInterval(() => {
      const type = logTypes[Math.floor(Math.random() * logTypes.length)] as 'INFO' | 'WARN' | 'AI_ENGINE';
      const messages = mockMessages[type];
      const message = messages[Math.floor(Math.random() * messages.length)];
      
      const newLog = `[${new Date().toLocaleTimeString()}] [${type}] ${message}`;
      
      setLogs((prev) => {
        const next = [...prev, newLog];
        // Keep last 15 logs
        return next.slice(-15);
      });
    }, 4000);

    return () => clearInterval(interval);
  }, [isStreaming]);

  // Scroll to bottom on new logs
  useEffect(() => {
    if (logFeedEndRef.current && typeof logFeedEndRef.current.scrollIntoView === 'function') {
      logFeedEndRef.current.scrollIntoView({ behavior: 'smooth' });
    }
  }, [logs]);

  return (
    <div className="flex flex-col gap-6 w-full p-4">
      {/* KPI Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <StatCard
          title="API Response Latency"
          value="122 ms"
          icon={<Server className="w-5 h-5 text-primary" />}
          trend={{ value: 'Operational', direction: 'neutral' }}
          aiSummary="Direct Supabase edge execution bypasses API gateways."
        />

        <StatCard
          title="CPU Core Utilization"
          value="24.8 %"
          icon={<Cpu className="w-5 h-5 text-accent" />}
          trend={{ value: 'Normal', direction: 'neutral', label: '8-core host' }}
          aiSummary="Webpack/Turbopack rendering engine fully optimized."
        />

        <StatCard
          title="DB Connection Pools"
          value="18 / 100"
          icon={<Radio className="w-5 h-5 text-success" />}
          trend={{ value: 'Safe', direction: 'neutral' }}
          aiSummary="Supabase pgbouncer pooled sockets active."
        />
      </div>

      {/* Terminal log panel */}
      <Card className="flex flex-col h-[480px] overflow-hidden" animate={true}>
        <CardHeader className="border-b-0 pb-2">
          <CardTitle className="flex gap-2 items-center text-lg sm:text-xl font-heading">
            <Terminal className="w-5.5 h-5.5 text-red-500" />
            Live System Diagnostic Terminal
          </CardTitle>
          <CardDescription className="text-xs sm:text-sm text-muted">
            Live-scrolling audit logs of turnstiles, database sockets, and AI reasoning updates.
          </CardDescription>
        </CardHeader>
        
        {/* Terminal Window Wrapper Inset */}
        <div className="flex-grow flex flex-col mx-6 mb-6 border border-card-border/60 rounded-xl overflow-hidden bg-slate-950 shadow-md">
          {/* Simulated Window Control Header */}
          <div className="flex items-center justify-between px-4 py-2.5 bg-slate-900 border-b border-slate-800/80 select-none">
            <div className="flex items-center gap-1.5">
              <span className="w-2.5 h-2.5 rounded-full bg-red-500/85" />
              <span className="w-2.5 h-2.5 rounded-full bg-amber-500/85" />
              <span className="w-2.5 h-2.5 rounded-full bg-success/85" />
            </div>
            <span className="text-[9px] uppercase tracking-widest text-slate-500 font-mono font-bold">
              aegis-diagnostics-sh
            </span>
            <div className="w-10" />
          </div>

          <CardContent className="overflow-y-auto flex-grow p-4 font-mono text-[10px] text-slate-400 flex flex-col gap-1.5 select-all">
            {logs.map((log, idx) => {
              const isWarn = log.includes('[WARN]');
              const isAi = log.includes('[AI_ENGINE]');
              
              let color = 'text-slate-400';
              if (isWarn) color = 'text-amber-500 font-bold';
              else if (isAi) color = 'text-purple-400 font-bold';
              
              return (
                <div key={idx} className={color}>
                  {log}
                </div>
              );
            })}
            <div ref={logFeedEndRef} />
          </CardContent>
        </div>
      </Card>
    </div>
  );
}
